
- hosts: all
  roles:
  - mariadb
  - php
  - role: oefenweb.wordpress
    become: true
  - role: wordpress-config
    become: true
  - role: apache
    become: true
    tags: apache
    when: install_apache
  - role: oersi-plugin
    become: true
    when: install_oersi_plugin
    tags: oersi-plugin